# 一、NumPy 库

NumPy(Numerical Python) 是 Python 语言的一个扩展程序库，支持大量的维度数组与矩阵运算，此外也针对数组运算提供了大量的数学函数库。

In [1]:
import numpy as np

# 二、NumPy 库数据结构——ndarray

## 1. 初识ndarry

In [2]:
a = (1, 2, 3, 4, 5)

In [3]:
a

(1, 2, 3, 4, 5)

In [4]:
type(a)

tuple

In [5]:
b = [1, 2, 3, 4, 5]

In [6]:
b

[1, 2, 3, 4, 5]

In [7]:
type(b)

list

In [8]:
c = np.array([1, 2, 3, 4, 5])

In [9]:
c

array([1, 2, 3, 4, 5])

In [10]:
b_ = np.array(b)

In [11]:
b_

array([1, 2, 3, 4, 5])

In [12]:
d = [[1, 2 ,3], [4, 5, 6]]
d

[[1, 2, 3], [4, 5, 6]]

In [13]:
e = np.array(d)
e

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
f = np.array([[1, 2, 3], [4, 5]])
f

array([list([1, 2, 3]), list([4, 5])], dtype=object)

In [15]:
g = np.array([1,None, 3, 'bo', (1,2)])

In [16]:
type(g[0])

int

In [17]:
g.dtype

dtype('O')

### 备注：

1. 元组，一种固定长度的，不可变的python对象序列

2. 列表，长度可变的，内容可修改的序列

3. ndarray，高效多维同类数据容器，支持矩阵

### NumPy 数据类型:

      int8/int16/int32——整数类型

      float16/float32/float64/float128——浮点数类型

      object——object类型

      bool——布尔值类型

      string_——字符串类型

      unicode_——unicode类型

      complex64/complex128/complex256——复数类型

## 2. ndarray 的属性和方法

In [18]:
e.shape

(2, 3)

In [19]:
e_ = e.reshape(3, 2)

In [20]:
e_

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
e_ = e.reshape(4, 2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [22]:
e.dtype

dtype('int32')

In [23]:
e.ndim

2

In [24]:
e.reshape(2,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [25]:
e_int8 = e.astype("int8")

In [26]:
e_int8

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [27]:
e_float32 = e.astype("float32")

In [28]:
e_float32

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [29]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
e.dtype

dtype('int32')

# 三、ndarray 运算

## 1. ndarray 矩阵运算

In [31]:
a = [1, 2, 3]
b = [4, 5, 6]
a + b

[1, 2, 3, 4, 5, 6]

In [32]:
a_ = np.array(a)
b_ = np.array(b)

In [33]:
a_

array([1, 2, 3])

In [34]:
b_

array([4, 5, 6])

In [35]:
a_ + b_

array([5, 7, 9])

In [36]:
a_ - 1

array([0, 1, 2])

In [37]:
a_ * 3

array([3, 6, 9])

In [38]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 2. ndarray 通用函数计算

### 2.1 一元通用函数：接收一个ndarray对象，并进行逐元素操作

In [40]:
a_

array([1, 2, 3])

In [41]:
np.square(a)

array([1, 4, 9], dtype=int32)

In [42]:
np.sqrt(a_)

array([1.        , 1.41421356, 1.73205081])

In [43]:
np.sqrt(a_).dtype

dtype('float64')

### 2.2 二元通用函数：接收两个ndarray对象，并进行计算操作

In [44]:
a_

array([1, 2, 3])

In [45]:
b_

array([4, 5, 6])

In [46]:
np.add(a_,b_)

array([5, 7, 9])

In [47]:
np.multiply(a_,b_)

array([ 4, 10, 18])

In [48]:
a

[1, 2, 3]

In [49]:
b

[4, 5, 6]

In [50]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [51]:
np.add(a, b)

array([5, 7, 9])

## 3. ndarray 基础统计方法

In [52]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
e.sum(axis = 0)

array([5, 7, 9])

In [54]:
e.sum(axis = 1)

array([ 6, 15])

In [55]:
e.max(axis = 0)

array([4, 5, 6])

In [56]:
e.min(axis = 1)

array([1, 4])

In [57]:
e.argmax(axis = 0)

array([1, 1, 1], dtype=int64)

In [58]:
e.argmin(axis = 1)

array([0, 0], dtype=int64)

## 小结

一、NumPy库

二、Numpy库核心——ndarray

1.初识ndarray

2.ndarray的属性和方法

三、ndarray 运算

1.ndarray 矩阵运算

2.ndarray 通用函数计算

3.ndarray 基础统计方法

# 四、 ndarray 切片与索引

## 1. 基础索引与切片

In [59]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

In [60]:
a[4]

5

In [61]:
a[2:4]

array([3, 4])

In [62]:
a_  = a.reshape(4,4)
a_

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [63]:
a_[2]

array([ 9, 10, 11, 12])

In [64]:
a_[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
a_[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
a_[:,2]

array([ 3,  7, 11, 15])

In [67]:
a_[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [68]:
a_[:2,:2]

array([[1, 2],
       [5, 6]])

In [69]:
a_[:2,:2] = 5

In [70]:
a_

array([[ 5,  5,  3,  4],
       [ 5,  5,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
a_[::2,::2]

array([[ 5,  3],
       [ 9, 11]])

In [72]:
a_[::1,::1]

array([[ 5,  5,  3,  4],
       [ 5,  5,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## 2. 布尔值索引

In [73]:
person = np.array(["A","B","C","D","E","F","G"])

In [74]:
group = np.array([1, 2, 1, 1, 1, 2, 2])

In [75]:
group == 1

array([ True, False,  True,  True,  True, False, False])

In [76]:
person[group == 1]

array(['A', 'C', 'D', 'E'], dtype='<U1')

# 五、ndarray 删除操作

In [77]:
a = [1, 2, 3, 4, 5]

In [78]:
a.pop(3)

4

In [79]:
a

[1, 2, 3, 5]

In [80]:
a.append(6)

In [81]:
a

[1, 2, 3, 5, 6]

In [82]:
a.insert(0,0)

In [83]:
a

[0, 1, 2, 3, 5, 6]

In [84]:
group

array([1, 2, 1, 1, 1, 2, 2])

In [85]:
group.pop

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [86]:
group.append

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [87]:
group.insert

AttributeError: 'numpy.ndarray' object has no attribute 'insert'

In [88]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
np.delete(a, 1, axis = 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

# 六、ndarray 合并操作

In [90]:
b = a

In [91]:
a + b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [92]:
np.concatenate((a, b),axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
np.concatenate((a, b),axis = 1)

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [94]:
b_ = b.T

In [95]:
b_

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [96]:
np.concatenate((a, b_),axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

# 七、Numpy 其他常用函数或方法

## 1. 一维数组生成函数

In [97]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
b = np.arange(3, 9)
b

array([3, 4, 5, 6, 7, 8])

In [99]:
b = np.arange(3, 9, 2)
b

array([3, 5, 7])

In [100]:
c = range(10)
c

range(0, 10)

In [101]:
list(c)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [102]:
h = np.linspace(0, 10, 5)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [103]:
i = np.logspace(-2, 2, 50)
i

array([1.00000000e-02, 1.20679264e-02, 1.45634848e-02, 1.75751062e-02,
       2.12095089e-02, 2.55954792e-02, 3.08884360e-02, 3.72759372e-02,
       4.49843267e-02, 5.42867544e-02, 6.55128557e-02, 7.90604321e-02,
       9.54095476e-02, 1.15139540e-01, 1.38949549e-01, 1.67683294e-01,
       2.02358965e-01, 2.44205309e-01, 2.94705170e-01, 3.55648031e-01,
       4.29193426e-01, 5.17947468e-01, 6.25055193e-01, 7.54312006e-01,
       9.10298178e-01, 1.09854114e+00, 1.32571137e+00, 1.59985872e+00,
       1.93069773e+00, 2.32995181e+00, 2.81176870e+00, 3.39322177e+00,
       4.09491506e+00, 4.94171336e+00, 5.96362332e+00, 7.19685673e+00,
       8.68511374e+00, 1.04811313e+01, 1.26485522e+01, 1.52641797e+01,
       1.84206997e+01, 2.22299648e+01, 2.68269580e+01, 3.23745754e+01,
       3.90693994e+01, 4.71486636e+01, 5.68986603e+01, 6.86648845e+01,
       8.28642773e+01, 1.00000000e+02])

## 2. 多维数组生成函数

In [104]:
a = np.zeros((3, 5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [105]:
b = np.ones((2, 4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 3. 随机数生成

In [106]:
a = np.random.randint(0, 20, size = (3, 5))
a

array([[10,  2, 15,  3, 18],
       [19, 19, 15,  8,  3],
       [ 0,  9, 14,  9, 10]])

In [107]:
b = np.random.normal(size=(3,5))
b

array([[-0.39876998, -3.18802773, -0.59966543, -0.63054271,  0.29046826],
       [ 2.08228931, -1.47918602,  0.04731244,  1.06674045,  1.32635611],
       [ 1.16970738,  1.44315663, -2.25150722,  0.64030745,  0.12519226]])

In [108]:
np.random.seed(121)
b = np.random.normal(size=(3,5))
b

array([[-0.21203317, -0.28492917, -0.57389821, -0.44031017, -0.33011056],
       [ 1.18369457,  1.61537293,  0.36706247, -0.01411931,  0.6296418 ],
       [ 1.70964074, -1.32698736,  0.40187312, -0.19142667,  1.40382596]])

In [109]:
np.random.seed(121)
b = np.random.normal(size=(3,5))
b

array([[-0.21203317, -0.28492917, -0.57389821, -0.44031017, -0.33011056],
       [ 1.18369457,  1.61537293,  0.36706247, -0.01411931,  0.6296418 ],
       [ 1.70964074, -1.32698736,  0.40187312, -0.19142667,  1.40382596]])

In [110]:
np.random.permutation([1,2,3,4,5,6])

array([2, 1, 4, 6, 5, 3])

## 小结

一、NumPy库

二、Numpy库核心——ndarray

1.初识ndarray

2.ndarray的属性和方法

三、ndarray 运算

1.ndarray 矩阵运算

2.ndarray 通用函数计算

3.ndarray 基础统计方法

四、ndarray 切片与索引

1.基础切片与索引

2.布尔值索引

五、ndarray 删除操作

六、ndarray 合并操作

七、NumPy 其他常用函数或方法

1.一维数组生成函数

2.多维数组生成函数

3.随机数生成