# 一、导入数据

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel("input/data_.xlsx",index_col=0)

In [3]:
data_ = data.copy()
data_

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
ID                                                                            
1275807                4                        2                         4   
1193683                1                        1                         2   
1170419               10                       10                        10   
1190386                4                        6                         6   
1202125                4                        1                         1   
...                  ...                      ...                       ...   
493452                 1                        1                         3   
1116132                6                        3                         4   
1133136                3                        1                         1   
1158247                1                        1                         1   
1206314                1                        2                         3   

         Marginal Adhesion  Single Epithelial Cell Size  Bare Nuclei  \
ID                                                                     
1275807                  3                            2            2   
1193683                  1                            3            1   
1170419                  8                            2           10   
1190386                  5                            7            6   
1202125                  1                            2            1   
...                    ...                          ...          ...   
493452                   1                            2            1   
1116132                  1                            5            2   
1133136                  1                            2            3   
1158247                  1                            2            1   
1206314                  1                            2            1   

         Bland Chromatin  Normal Nucleoli  Mitoses  Class  Thickness_classnum  \
ID                                                                              
1275807                2                1        1      2                   2   
1193683                1                1        1      2                   1   
1170419                4                1        1      4                   3   
1190386                7                7        3      4                   2   
1202125                3                1        1      2                   2   
...                  ...              ...      ...    ...                 ...   
493452                 1                1        1      2                   1   
1116132                3                9        1      4                   2   
1133136                3                1        1      2                   1   
1158247                2                1        1      2                   1   
1206314                1                1        1      2                   1   

         Cell Size _small  Cell Size _medium  Cell Size _big Thickness_class  \
ID                                                                             
1275807                 1                  0               0          medium   
1193683                 1                  0               0            thin   
1170419                 0                  0               1           thick   
1190386                 0                  1               0          medium   
1202125                 1                  0               0          medium   
...                   ...                ...             ...             ...   
493452                  1                  0               0            thin   
1116132                 1                  0               0          medium   
1133136                 1                  0               0            thin   
1158247                 1                  0               0            thin   
1206314                 1     

In [4]:
data_.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 645 entries, 1275807 to 1206314
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Clump Thickness              645 non-null    int64 
 1   Uniformity of Cell Size      645 non-null    int64 
 2   Uniformity of Cell Shape     645 non-null    int64 
 3   Marginal Adhesion            645 non-null    int64 
 4   Single Epithelial Cell Size  645 non-null    int64 
 5   Bare Nuclei                  645 non-null    int64 
 6   Bland Chromatin              645 non-null    int64 
 7   Normal Nucleoli              645 non-null    int64 
 8   Mitoses                      645 non-null    int64 
 9   Class                        645 non-null    int64 
 10  Thickness_classnum           645 non-null    int64 
 11  Cell Size _small             645 non-null    int64 
 12  Cell Size _medium            645 non-null    int64 
 13  Cell Size _big           

# 二、设置变量

In [5]:
features = data_.drop(columns=['Class','Thickness_class','Cell Size'])
features

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
ID                                                                            
1275807                4                        2                         4   
1193683                1                        1                         2   
1170419               10                       10                        10   
1190386                4                        6                         6   
1202125                4                        1                         1   
...                  ...                      ...                       ...   
493452                 1                        1                         3   
1116132                6                        3                         4   
1133136                3                        1                         1   
1158247                1                        1                         1   
1206314                1                        2                         3   

         Marginal Adhesion  Single Epithelial Cell Size  Bare Nuclei  \
ID                                                                     
1275807                  3                            2            2   
1193683                  1                            3            1   
1170419                  8                            2           10   
1190386                  5                            7            6   
1202125                  1                            2            1   
...                    ...                          ...          ...   
493452                   1                            2            1   
1116132                  1                            5            2   
1133136                  1                            2            3   
1158247                  1                            2            1   
1206314                  1                            2            1   

         Bland Chromatin  Normal Nucleoli  Mitoses  Thickness_classnum  \
ID                                                                       
1275807                2                1        1                   2   
1193683                1                1        1                   1   
1170419                4                1        1                   3   
1190386                7                7        3                   2   
1202125                3                1        1                   2   
...                  ...              ...      ...                 ...   
493452                 1                1        1                   1   
1116132                3                9        1                   2   
1133136                3                1        1                   1   
1158247                2                1        1                   1   
1206314                1                1        1                   1   

         Cell Size _small  Cell Size _medium  Cell Size _big  
ID                                                            
1275807                 1                  0               0  
1193683                 1                  0               0  
1170419                 0                  0               1  
1190386                 0                  1               0  
1202125                 1                  0               0  
...                   ...                ...             ...  
493452                  1                  0               0  
1116132                 1                  0               0  
1133136                 1                  0               0  
1158247                 1                  0               0  
1206314                 1                  0               0  

[645 rows x 13 columns]

In [6]:
target = data_.Class.replace(to_replace = [2, 4], value = [0,1])
target

ID
1275807    0
1193683    0
1170419    1
1190386    1
1202125    0
          ..
493452     0
1116132    1
1133136    0
1158247    0
1206314    0
Name: Class, Length: 645, dtype: int64

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
transfer = StandardScaler()

In [9]:
features_ = transfer.fit_transform(features)

In [10]:
features_

array([[-0.17231198, -0.39676889,  0.23516391, ...,  0.62217102,
        -0.47319015, -0.32610809],
       [-1.22412169, -0.72153531, -0.43303311, ...,  0.62217102,
        -0.47319015, -0.32610809],
       [ 1.93130744,  2.20136243,  2.23975499, ..., -1.60727513,
        -0.47319015,  3.06646797],
       ...,
       [-0.52291521, -0.72153531, -0.76713162, ...,  0.62217102,
        -0.47319015, -0.32610809],
       [-1.22412169, -0.72153531, -0.76713162, ...,  0.62217102,
        -0.47319015, -0.32610809],
       [-1.22412169, -0.39676889, -0.0989346 , ...,  0.62217102,
        -0.47319015, -0.32610809]])

# 三、拆分数据集

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
train_features, test_features, train_target, test_target = train_test_split(
    features, target, 
    test_size = 145, random_state = 99)

In [13]:
print(train_features.shape)
print(train_target.shape)
print(test_features.shape)
print(test_target.shape)

(500, 13)
(500,)
(145, 13)
(145,)


# 四、Voting Classifier

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [15]:
log_clf = LogisticRegression()
svm_clf = SVC()
tree_clf = DecisionTreeClassifier()

In [16]:
from sklearn.ensemble import VotingClassifier

In [17]:
voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('svc', svm_clf), ('tree', tree_clf)],
    voting='hard')

In [18]:
voting_clf.fit(train_features, train_target)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('svc',
                              SVC(C=1.0, break_ties=False, cache_size=200,
                                  class_weight=None, coef0=0.0,
                                  d...
                              DecisionTreeClassifier(ccp_alpha=0.0,
       

In [19]:
for clf in (log_clf, tree_clf, svm_clf, voting_clf):
    clf.fit(train_features, train_target)
    print(clf.__class__.__name__, clf.score(test_features, test_target))

LogisticRegression 0.9862068965517241
DecisionTreeClassifier 0.9517241379310345
SVC 0.993103448275862
VotingClassifier 0.9862068965517241


In [20]:
#voting_clf.predict_proba(test_features)

In [21]:
log_clf = LogisticRegression()
svm_clf = SVC(probability=True)
tree_clf = DecisionTreeClassifier()

In [22]:
voting_clf = VotingClassifier(
    estimators=[('lr', log_clf), ('svc', svm_clf), ('tree', tree_clf)],
    voting='soft')

In [23]:
voting_clf.fit(train_features, train_target)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('svc',
                              SVC(C=1.0, break_ties=False, cache_size=200,
                                  class_weight=None, coef0=0.0,
                                  d...
                              DecisionTreeClassifier(ccp_alpha=0.0,
       

In [24]:
voting_clf.predict_proba(test_features)

array([[0.99801794, 0.00198206],
       [0.01946127, 0.98053873],
       [0.0135109 , 0.9864891 ],
       [0.99840628, 0.00159372],
       [0.00707732, 0.99292268],
       [0.35667523, 0.64332477],
       [0.99757498, 0.00242502],
       [0.00969531, 0.99030469],
       [0.99761151, 0.00238849],
       [0.01460224, 0.98539776],
       [0.014371  , 0.985629  ],
       [0.99314418, 0.00685582],
       [0.01983322, 0.98016678],
       [0.99835601, 0.00164399],
       [0.99657204, 0.00342796],
       [0.9389349 , 0.0610651 ],
       [0.99796965, 0.00203035],
       [0.99848653, 0.00151347],
       [0.87295013, 0.12704987],
       [0.99835601, 0.00164399],
       [0.00735395, 0.99264605],
       [0.97539894, 0.02460106],
       [0.99848653, 0.00151347],
       [0.99587659, 0.00412341],
       [0.99004573, 0.00995427],
       [0.99848653, 0.00151347],
       [0.01564669, 0.98435331],
       [0.99801794, 0.00198206],
       [0.98976833, 0.01023167],
       [0.98830406, 0.01169594],
       [0.

In [25]:
for clf in (log_clf, tree_clf, svm_clf, voting_clf):
    clf.fit(train_features, train_target)
    print(clf.__class__.__name__, clf.score(test_features, test_target))

LogisticRegression 0.9862068965517241
DecisionTreeClassifier 0.9448275862068966
SVC 0.993103448275862
VotingClassifier 0.9793103448275862


# 五、Stacking

In [26]:
from sklearn.ensemble import StackingClassifier

In [27]:
log_clf = LogisticRegression()
svm_clf = SVC(probability=True)
tree_clf = DecisionTreeClassifier()

In [28]:
log_ensemble = LogisticRegression()

In [29]:
stk_clf = StackingClassifier(
      estimators=[('lr', log_clf), ('svc', svm_clf), ('tree', tree_clf)],
    final_estimator=log_ensemble)

In [30]:
stk_clf.fit(train_features, train_target)

StackingClassifier(cv=None,
                   estimators=[('lr',
                                LogisticRegression(C=1.0, class_weight=None,
                                                   dual=False,
                                                   fit_intercept=True,
                                                   intercept_scaling=1,
                                                   l1_ratio=None, max_iter=100,
                                                   multi_class='auto',
                                                   n_jobs=None, penalty='l2',
                                                   random_state=None,
                                                   solver='lbfgs', tol=0.0001,
                                                   verbose=0,
                                                   warm_start=False)),
                               ('svc',
                                SVC(C=1.0, break_ties=False, cache_size=200,
                        

In [31]:
stk_clf.score(test_features, test_target)

0.9862068965517241

# 六、Bagging

In [32]:
from sklearn.ensemble import BaggingClassifier

In [33]:
bag_clf = BaggingClassifier(
    DecisionTreeClassifier(), n_estimators=500,
    max_samples=100, max_features=9,
    bootstrap=True, oob_score=True,
    random_state=99)

In [34]:
bag_clf.fit(train_features, train_target)

BaggingClassifier(base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                        class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort='deprecated',
                                                        random_state=None,


In [35]:
bag_clf.oob_score_

0.964

In [36]:
bag_clf.score(test_features, test_target)

0.9793103448275862

# 七、Boosting

In [37]:
from sklearn.ensemble import AdaBoostClassifier

In [38]:
ada_clf = AdaBoostClassifier(
    DecisionTreeClassifier(), n_estimators=500, learning_rate=0.5)

In [39]:
ada_clf.fit(train_features,train_target)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort='deprecated',
                       

In [40]:
ada_clf.score(test_features,test_target)

0.9379310344827586

In [41]:
from sklearn.ensemble import GradientBoostingClassifier

In [42]:
gra_clf = GradientBoostingClassifier(n_estimators=500, learning_rate=0.5)#Gradient Tree Boosting

In [43]:
gra_clf.fit(train_features,train_target)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.5, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=500,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [44]:
gra_clf.score(test_features,test_target)

0.9379310344827586

In [45]:
ada_clf.feature_importances_

array([0.02997349, 0.70898075, 0.04505754, 0.01103513, 0.05268977,
       0.07516707, 0.        , 0.05450466, 0.        , 0.0112958 ,
       0.        , 0.0112958 , 0.        ])

In [46]:
gra_clf.feature_importances_

array([0.04847922, 0.56866424, 0.02334067, 0.00771243, 0.01864861,
       0.21530579, 0.06211193, 0.04553155, 0.00081415, 0.00626333,
       0.00145682, 0.00167124, 0.        ])

# 八、随机森林

In [47]:
from sklearn.ensemble import RandomForestClassifier

In [48]:
rfc_clf = RandomForestClassifier(n_estimators=500,max_samples=100,max_features=9,random_state=99)

In [49]:
rfc_clf.fit(train_features,train_target)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=9,
                       max_leaf_nodes=None, max_samples=100,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=99, verbose=0,
                       warm_start=False)

In [50]:
rfc_clf.score(test_features,test_target)

0.9793103448275862

In [51]:
rfc_clf.feature_importances_

array([0.04444294, 0.27972714, 0.17882586, 0.0228714 , 0.06050002,
       0.228914  , 0.10063741, 0.04794112, 0.00589252, 0.01099854,
       0.01688998, 0.00161953, 0.00073954])

# 九、Xgboost

In [52]:
import xgboost

In [53]:
xgb_clf = xgboost.XGBClassifier(n_estimators=500,learning_rate=0.5)

In [54]:
xgb_clf.fit(train_features, train_target)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.5, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=500, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [55]:
xgb_clf.score(test_features, test_target)

0.9448275862068966

In [56]:
xgb_clf.feature_importances_

array([0.06066684, 0.38067472, 0.10667446, 0.03279881, 0.00560918,
       0.17975621, 0.09092688, 0.02961534, 0.11259985, 0.        ,
       0.        , 0.00067777, 0.        ], dtype=float32)